const assets = {
    assassin: '/assets/assassin.jpg',
    away: '/assets/away.jpg',
    background: '/assets/background.png',
    cod: '/assets/cod.jpg',
    dmc5: '/assets/dmc5.jpg',
    finalfantasy: '/assets/finalfantasy.jpg',
    garis: '/assets/garis.svg',
    gow: '/assets/gow.jpg',
    pict: '/assets/pict.jpg',
    ps5: '/assets/ps5.jpg',
    pumpItUp: '/assets/pumpItUp.jpg',
    re2: '/assets/re2.jpg',
    re3: '/assets/re3.jpg',
    rog: '/assets/rog.jpg',
    spiderman: '/assets/spiderman.jpg',
    tekken: '/assets/tekken.jpg',
    turismo: '/assets/turismo.jpg',
    watchdog: '/assets/watchdog.jpg',
    xbox: '/assets/xbox.jpg',
    logo: '/assets/logo.png',
    EldenRing : '/assets/EldenRing.jpg',
    fifa : '/assets/fifa.jpg',
    ghost : '/assets/ghost.jpg',
    godOfwar : '/assets/godOfwar.jpg',
    gtaV : '/assets/gtaV.jpg',
    itTakestwo : '/assets/itTakestwo.jpg',
    miles : '/assets/miles.jpg',
    stray : '/assets/stray.jpg',
    mw2 : '/assets/mw2.jpg',
    nba : '/assets/nba.jpg',
    pes : '/assets/pes.jpg',
    StreetFighter6 : '/assets/StreetFighter6.jpg',
    uncharted : '/assets/uncharted.jpg',
    untilDawn : '/assets/untilDawn.jpg',
    valhalla : '/assets/valhalla.jpg'
  };
  
  export default assets;
  